export const end_category = [
  { id: 73, name: 'Rice', image: 'https://media.istockphoto.com/photos/dry-white-long-rice-basmati-in-wooden-bowl-and-burlap-sack-with-on-picture-id1193536444?k=20&m=1193536444&s=612x612&w=0&h=QveYIc3ZekC0oPZcda9Ab65LaTeYL9af_6FI2aWcPN8=', mcatId: 22, tcatId: 6 },
  {
    id: 76,
    name: 'Fresh Fruits',
    image: 'https://www.bestfreshfruits.com/wp-content/uploads/2015/09/frutas_7.png',
    mcatId: 38,
    tcatId: 6,
  },
  {
    id: 77,
    name: 'Fresh Vegetables',
    image: 'https://4.imimg.com/data4/AY/TE/IMOB-27708947/c__data_users_defapps_appdata_internetexplorer_temp_sav-500x500.jpg',
    mcatId: 38,
    tcatId: 6,
  },
  {
    id: 78,
    name: 'Premium Ingredients',
    image: 'https://cdn.winsightmedia.com/platform/files/public/2018-05/background/800x420/superfoods_1527793079.jpg',
    mcatId: 22,
    tcatId: 6,
  },
  {
    id: 79,
    name: 'Colors & Flavours',
    image: 'https://shebaonlinebd.com/wp-content/uploads/c2-1.jpg',
    mcatId: 22,
    tcatId: 6,
  },
  {
    id: 80,
    name: 'Pickles',
    image: 'https://media.istockphoto.com/photos/pouring-brine-into-a-pickling-jar-picture-id1330338331?b=1&k=20&m=1330338331&s=170667a&w=0&h=nDH5M1ZyDniS_5Rxqm6BLYW5UU2mQfxZssppTNUhRVg=',
    mcatId: 22,
    tcatId: 6,
  },
  {
    id: 81,
    name: 'Spices',
    image: 'endCatagori81.webp',
    mcatId: 22,
    tcatId: 6,
  },
  { id: 85, name: 'Oil', image: 'endCatagori85.webp', mcatId: 22, tcatId: 6 },
  { id: 86, name: 'Ghee', image: 'endCatagori86.webp', mcatId: 22, tcatId: 6 },
  {
    id: 88,
    name: 'Ready Mix',
    image: 'endCatagori88.webp',
    mcatId: 22,
    tcatId: 6,
  },
  {
    id: 89,
    name: 'Salt & Sugar',
    image: 'endCatagori89.webp',
    mcatId: 22,
    tcatId: 6,
  },
  {
    id: 91,
    name: 'Dal or Lentil',
    image: 'endCatagori91.webp',
    mcatId: 22,
    tcatId: 6,
  },
  {
    id: 92,
    name: 'Shemai & Suji',
    image: 'endCatagori92.webp',
    mcatId: 22,
    tcatId: 6,
  },
  {
    id: 93,
    name: 'Special Ingredients',
    image: 'eindCatagori12.webp',
    mcatId: 22,
    tcatId: 6,
  },
  { id: 94, name: 'Tea', image: 'endCatagori94.webp', mcatId: 30, tcatId: 6 },
  {
    id: 95,
    name: 'Coffee',
    image: 'endCatagori95.webp',
    mcatId: 30,
    tcatId: 6,
  },
  { id: 96, name: 'Juice', image: 'topcatagori0.webp', mcatId: 30, tcatId: 6 },
  {
    id: 97,
    name: 'Noodles',
    image: 'topcatagorinoodles.webp.webp',
    mcatId: 28,
    tcatId: 6,
  },
  {
    id: 98,
    name: 'Soups',
    image: 'topcatagorisoups.webp.webp',
    mcatId: 28,
    tcatId: 6,
  },
];

export const mid_category = [
  {
    id: 22,
    name: 'Cooking',
    image: 'https://s3.ap-southeast-1.amazonaws.com/images.deccanchronicle.com/dc-Cover-h5859g6k3s59c6voh464b0q851-20201106131909.Medi.jpeg',
    tCatId: 6,
    slug: 'grocery-&-food/cooking',
  },
  {
    id: 23,
    name: 'Baking Needs',
    image: 'https://chaldn.com/_mpimage/baking-ingredients?src=https%3A%2F%2Feggyolk.chaldal.com%2Fapi%2FPicture%2FRaw%3FpictureId%3D28687&q=low&v=1&m=400',
    tCatId: 6,
    slug: 'grocery-&-food/baking-needs',
  },
  {
    id: 24,
    name: 'Breakfast',
    image: 'https://www.tasteofhome.com/wp-content/uploads/2018/01/Breakfast-Wraps_EXPS_TOHPP19_35683_B08_23_6b.jpg',
    tCatId: 6,
    slug: 'grocery-&-food/breakfast',
  },
  {
    id: 25,
    name: 'Bread & Bakery',
    image: 'https://thefinancialexpress.com.bd/uploads/1611556926.jpg',
    tCatId: 6,
    slug: 'grocery-&-food/bread-&-bakery',
  },
  {
    id: 26,
    name: 'Frozen & Canned',
    image: 'https://a99d9b858c7df59c454c-96c6baa7fa2a34c80f17051de799bc8e.ssl.cf1.rackcdn.com/images/frozen-fresh-vegetables.jpg',
    tCatId: 6,
    slug: 'grocery-&-food/frozen-&-canned',
  },
  {
    id: 27,
    name: 'Dairy',
    image: 'https://cdn-a.william-reed.com/var/wrbm_gb_food_pharma/storage/images/publications/food-beverage-nutrition/nutraingredients.com/news/research/global-study-links-high-fat-dairy-consumption-to-blood-and-heart-health/11403932-1-eng-GB/Global-study-links-high-fat-dairy-consumption-to-blood-and-heart-health.jpg',
    tCatId: 6,
    slug: 'grocery-&-food/dairy',
  },
  {
    id: 28,
    name: 'Snacks',
    image: 'mitLavaleCatagori28.webp',
    tCatId: 6,
    slug: 'grocery-&-food/snacks',
  },
  {
    id: 29,
    name: 'Meat & Fish',
    image: 'mitLavaleCatagori29.webp',
    tCatId: 6,
    slug: 'grocery-&-food/meat-&-fish',
  },
  {
    id: 30,
    name: 'Beverages',
    image: 'mitLavaleCatagoriBaverages.webp.webp',
    tCatId: 6,
    slug: 'grocery-&-food/beverages',
  },
  {
    id: 38,
    name: 'Fruits & Vegetables',
    image: 'mitLavaleCatagoriFruits & Vegetables.webp.webp',
    tCatId: 6,
    slug: 'grocery-&-food/fruits-&-vegetables',
  },
  {
    id: 41,
    name: 'Fooding',
    image: 'topcatagorifooding.webp.webp',
    tCatId: 11,
  },
  {
    id: 42,
    name: 'Bath & Skincare',
    image: 'topcatagoribath-skincare.webp.webp',
    tCatId: 11,
  },
  {
    id: 43,
    name: 'Diapers & Wipes',
    image: 'topcatagoridiapers-wipes.webp.webp',
    tCatId: 11,
  },
  {
    id: 44,
    name: 'Feeders',
    image: 'topcatagorifeeders.webp.webp',
    tCatId: 11,
  },
  {
    id: 45,
    name: 'Newborn Essentials',
    image: 'topcatagorinewborn-essentials.webp.webp',
    tCatId: 11,
  },
  {
    id: 46,
    name: 'Baby Accessories',
    image: 'topcatagoribaby-accessories.webp.webp',
    tCatId: 11,
  },
  {
    id: 47,
    name: 'Baby Oral Care',
    image: 'topcatagoribaby-oral-care.webp.webp',
    tCatId: 11,
  },
  {
    id: 48,
    name: 'Health Care',
    image: 'topcatagorihealth-care.webp.webp',
    tCatId: 12,
  },
  {
    id: 49,
    name: 'Personal Care',
    image: 'topcatagoripersonal-care.webp.webp',
    tCatId: 12,
  },
  {
    id: 50,
    name: 'Dish Detergents',
    image: 'topcatagoridish-detergents.webp.webp',
    tCatId: 13,
  },
  {
    id: 51,
    name: 'Cleaning Supplies',
    image: 'topcatagoricleaning-supplies.webp.webp',
    tCatId: 13,
  },
  {
    id: 52,
    name: 'Air Fresheners',
    image: 'topcatagoriair-fresheners.webp.webp',
    tCatId: 13,
  },
  {
    id: 53,
    name: 'Laundry',
    image: 'topcatagorilaundry.webp.webp',
    tCatId: 13,
  },
  {
    id: 54,
    name: 'Napkins & Paper Products',
    image: 'topcatagorinapkins-paper-products.webp.webp',
    tCatId: 13,
  },
  {
    id: 55,
    name: 'Pest Control',
    image: 'topcatagoripest-control.webp.webp',
    tCatId: 13,
  },
  {
    id: 56,
    name: 'Shoe Care',
    image: 'topcatagorishoe-care.webp.webp',
    tCatId: 13,
  },
  {
    id: 57,
    name: 'Lights & Electrical',
    image: 'topcatagorilights-electrical.webp.webp',
    tCatId: 14,
  },
  {
    id: 58,
    name: 'Tools & Hardware',
    image: 'topcatagoritools-hardware.webp.webp',
    tCatId: 14,
  },
  {
    id: 59,
    name: 'Kitchen Appliances',
    image: 'topcatagorikitchen-appliances.webp.webp',
    tCatId: 14,
  },
  {
    id: 60,
    name: 'Printing',
    image: 'topcatagoriprinting.webp.webp',
    tCatId: 9,
  },
  {
    id: 61,
    name: 'Writing & Drawing',
    image: 'topcatagoriwriting-drawing.webp.webp',
    tCatId: 9,
  },
  {
    id: 62,
    name: 'Organizing',
    image: 'topcatagoriorganizing.webp.webp',
    tCatId: 9,
  },
  {
    id: 63,
    name: 'Batteries',
    image: 'topcatagoribatteries.webp.webp',
    tCatId: 9,
  },
  {
    id: 64,
    name: 'Female Care',
    image: 'topcatagorifemale-care.webp.webp',
    tCatId: 12,
  },
  {
    id: 65,
    name: 'Male Care',
    image: 'topcatagorimale-care.webp.webp',
    tCatId: 12,
  },
];
// category
export const top_category = [
  {
    tCatId: 6,
    name: 'Grocery & Food',
    slug: 'grocery-&-food',
    image: 'https://s3.ap-south-1.amazonaws.com/cdn-shebaxyz/images/categories_images/thumbs/1586421846_shebagroceries.jpg',
    icon: 'GiFruitBowl',
  },
  {
    tCatId: 7,
    name: 'D Food',
    slug: 'd-food',
    image: 'https://www.eatthis.com/wp-content/uploads/sites/4/2018/12/vitamin-d-foods.jpg?quality=82&strip=all',
    icon: 'GiFruitBowl',
  },
  {
    tCatId: 8,
    name: 'D Pharmacy',
    slug: 'd-pharmacy',
    image: 'https://static.toiimg.com/photo/74336658.cms',
    icon: 'GiFruitBowl',
  },
  {
    tCatId: 9,
    name: 'Office Products',
    slug: 'office-products',
    image: 'https://m.foolcdn.com/media/the-blueprint/images/Office_Supplies_An_Asset-01-Office_Supplies.width-800.png',
    icon: 'GiFruitBowl',
  },
  {
    tCatId: 11,
    name: 'Baby Care',
    slug: 'baby-care',
    image: 'https://4.imimg.com/data4/DX/AO/MY-4573598/baby-care-products-kit-500x500.jpg',
    icon: 'GiFruitBowl',
  },
  {
    tCatId: 12,
    name: 'Beauty & Health',
    slug: 'beauty-&-health',
    image: 'https://www.sproutsanfrancisco.com/get-educated/wp-content/uploads/2019/01/personalcareproducts.jpg',
    icon: 'GiFruitBowl',
  },
  {
    tCatId: 13,
    name: 'Home & Cleaning',
    slug: 'home-&-cleaning',
    image: 'topcatagori13.webp',
    icon: 'GiFruitBowl',
  },
  {
    tCatId: 14,
    name: 'Home Appliances',
    image: 'topcatagori14.webp',
  },
];

export const products = [
  {
    id: 3,
    productName: 'Nazirshail Rice Premium 5 kg',
    mcatId: 23,
    oldPrice: '573',
    currentPrice: '348',
    qty: 485,
    image: 'https://i2.wp.com/www.khan.com.bd/wp-content/uploads/2020/12/Nazirshail-Rice-Premium.jpg?fit=1200%2C1200&ssl=1',
    totalView: 1,
    featured: 1,
    ecatId: 78,
  },
  {
    id: 4,
    productName: 'Chinigura Rice 1 kg',
    oldPrice: '573',
    mcatId: 24,
    currentPrice: '98',
    qty: 499,
    image: 'https://images.othoba.com/images/thumbs/0294809_chashi-aromatic-chinigura-rice-5-kg.jpeg',
    totalView: 3,
    featured: 1,
    ecatId: 78,
  },
  {
    id: 7,
    productName: 'Cumin Seed {Jira} 100 gm',
    oldPrice: '573',
    mcatId: 23,
    currentPrice: '39',
    qty: 49999,
    image: 'https://chomokbdshop.com/wp-content/uploads/2020/10/cuminseeds_deshibaza_JxpUY.jpg',
    totalView: 4,
    featured: 1,
    ecatId: 79,
  },
  {
    id: 8,
    productName: 'Cinnamon {Daruchini} 100 gm',
    oldPrice: '573',
    mcatId: 24,
    currentPrice: '49',
    qty: 49999,
    image: 'https://chomokbdshop.com/wp-content/uploads/2020/10/cuminseeds_deshibaza_JxpUY.jpg',
    totalView: 5,
    featured: 1,
    ecatId: 79,
  },
  {
    id: 9,
    productName: 'Cardamom {Elachi} 50 gm',
    oldPrice: '573',
    mcatId: 25,
    currentPrice: '149',
    qty: 50000,
    image: 'https://5.imimg.com/data5/AK/UF/MY-10017135/green-cardamom-250x250.jpg',
    totalView: 24,
    featured: 1,
    ecatId: 78,
  },
  {
    id: 10,
    productName: 'Rupchanda Soyabean Oil 5 ltr',
    oldPrice: '573',
    mcatId: 26,
    currentPrice: '685',
    qty: 50000,
    image: 'product-featured-10.webp',
    totalView: 371,
    featured: 1,
    ecatId: 78,
  },
  {
    id: 11,
    productName: 'Dried Chilies {Shukna Morich} 100 gm',
    oldPrice: '573',
    mcatId: 26,
    currentPrice: '39',
    qty: 50000,
    image: 'product-featured-11.webp',
    totalView: 376,
    featured: 1,
    ecatId: 78,
  },
  {
    id: 12,
    productName: 'Rupchanda Soyabean Oil 2 ltr',
    oldPrice: '573',
    mcatId: 27,
    currentPrice: '276',
    qty: 50000,
    image: 'product-featured-12.webp',
    totalView: 25,
    featured: 1,
    ecatId: 78,
  },
  {
    id: 13,
    productName: 'Cloves {Lobongo} 50 gm',
    oldPrice: '573',
    mcatId: 28,
    currentPrice: '59',
    qty: 50000,
    image: 'product-featured-13.webp',
    totalView: 386,
    featured: 1,
    ecatId: 79,
  },
  {
    id: 14,
    productName: 'Bay Leaves {Tejpata} 100 gm',
    oldPrice: '573',
    mcatId: 29,
    currentPrice: '19',
    qty: 50000,
    image: 'product-featured-14.webp',
    totalView: 55,
    featured: 1,
    ecatId: 78,
  },
];
